#!/bin/bash

## This script assumes that you have the rust toolchain installed

# Install embedded targets
rustup target add thumbv6m-none-eabi # For M0, M0+, M1 (Raspberry Pi Pico W)

# Install cargo-binutils
cargo install cargo-binutils
rustup component add llvm-tools-preview

# Install cargo-generate
cargo install cargo-generate

# Install node
curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - &&\
sudo apt-get install -y nodejs


# Fetch raspberry pi pico emulator
if [ ! -d "dependencies/rp2040js" ]; then
  cd tools
  git clone https://github.com/wokwi/rp2040js.git
  cd rp2040js
  git apply ../rp2040js.patch
  cd -
fi
